name: Feature Request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of the problem
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution
      description: What you would like to happen
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions you've considered
